execution:
    uuid: 18fb9e2f-c278-4d1c-aeea-b84e7b266f9b
    runtime:
        start: 2019-01-08T21:20:54.830799-05:00
        end: 2019-01-08T21:34:30.851909-05:00
        duration: 13 minutes, 36 seconds, and 21110 microseconds

action:
    type: method
    plugin: !ref 'environment:plugins:dada2'
    action: denoise_paired
    inputs:
    -   demultiplexed_seqs: dac21002-53ac-4782-8fb4-196ab077bfdf
    parameters:
    -   trunc_len_f: 160
    -   trunc_len_r: 160
    -   trim_left_f: 0
    -   trim_left_r: 0
    -   max_ee: 2.0
    -   trunc_q: 2
    -   chimera_method: consensus
    -   min_fold_parent_over_abundance: 1.0
    -   n_threads: 4
    -   n_reads_learn: 1000000
    -   hashed_feature_ids: true
    output-name: representative_sequences

transformers:
    inputs:
        demultiplexed_seqs:
        -   from: SingleLanePerSamplePairedEndFastqDirFmt
            to: SingleLanePerSamplePairedEndFastqDirFmt
    output:
    -   from: q2_types.feature_data._transformer:DNAIterator
        to: DNASequencesDirectoryFormat
        plugin: !ref 'environment:plugins:types'

environment:
    platform: macosx-10.9-x86_64
    python: |-
        3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:43:56)
        [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
    framework:
        version: 2018.11.0
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2018.11.0|0'
    plugins:
        types:
            version: 2018.11.0
            website: https://github.com/qiime2/q2-types
        dada2:
            version: 2018.11.0
            website: http://benjjneb.github.io/dada2/
            citations:
            - !cite 'plugin|dada2:2018.11.0|0'
    python-packages:
        xopen: 0.3.5
        widgetsnbextension: 3.4.2
        wheel: 0.32.0
        webencodings: 0.5.1
        wcwidth: 0.1.7
        urllib3: '1.23'
        unifrac: 0.9.2
        traitlets: 4.3.2
        tornado: 5.1.1
        testpath: 0.3.1
        terminado: 0.8.1
        statsmodels: 0.9.0
        six: 1.11.0
        simplegeneric: 0.8.1
        setuptools: 40.4.3
        Send2Trash: 1.5.0
        seaborn: 0.9.0
        scipy: 0.19.1
        scikit-learn: 0.19.1
        scikit-bio: 0.5.4
        requests: 2.19.1
        reportlab: 3.5.8
        qiime2: 2018.11.0
        q2templates: 2018.11.0
        q2cli: 2018.11.0
        q2-vsearch: 2018.11.0
        q2-types: 2018.11.0
        q2-taxa: 2018.11.0
        q2-sample-classifier: 2018.11.0
        q2-quality-filter: 2018.11.0
        q2-quality-control: 2018.11.0
        q2-phylogeny: 2018.11.0
        q2-metadata: 2018.11.0
        q2-longitudinal: 2018.11.0
        q2-gneiss: 2018.11.0
        q2-fragment-insertion: 2018.11.0
        q2-feature-table: 2018.11.0
        q2-feature-classifier: 2018.11.0
        q2-emperor: 2018.11.0
        q2-diversity: 2018.11.0
        q2-demux: 2018.11.0
        q2-deblur: 2018.11.0
        q2-dada2: 2018.11.0
        q2-cutadapt: 2018.11.0
        q2-composition: 2018.11.0
        q2-alignment: 2018.11.0
        pyzmq: 17.1.2
        PyYAML: '3.13'
        pytz: '2018.7'
        python-dateutil: 2.7.5
        PySocks: 1.6.8
        pyparsing: 2.3.0
        pyOpenSSL: 18.0.0
        Pygments: 2.2.0
        pycparser: '2.19'
        ptyprocess: 0.6.0
        psutil: 5.4.7
        prompt-toolkit: 2.0.7
        prometheus-client: 0.4.2
        pip: '18.0'
        Pillow: 5.3.0
        pickleshare: 0.7.5
        pexpect: 4.6.0
        patsy: 0.5.1
        parso: 0.3.1
        pandocfilters: 1.4.2
        pandas: 0.22.0
        packaging: '18.0'
        olefile: '0.46'
        numpy: 1.14.2
        notebook: 5.7.0
        nose: 1.3.7
        nbformat: 4.4.0
        nbconvert: 5.3.1
        natsort: 5.4.0
        msgpack: 0.5.6
        mistune: 0.8.3
        matplotlib: 2.2.3
        MarkupSafe: '1.0'
        lockfile: 0.12.2
        kiwisolver: 1.0.1
        jupyter-core: 4.4.0
        jupyter-client: 5.2.3
        jsonschema: 2.6.0
        Jinja2: '2.10'
        jedi: 0.12.1
        itsxpress: 1.7.2
        ipywidgets: 7.4.2
        ipython: 7.0.1
        ipython-genutils: 0.2.0
        ipykernel: 5.1.0
        idna: '2.7'
        hdmedians: '0.13'
        h5py: 2.7.0
        gneiss: 0.4.4
        future: 0.16.0
        fastcluster: 1.1.25
        entrypoints: 0.2.3
        emperor: 1.0.0b18
        decorator: 4.3.0
        deblur: 1.1.0
        Cython: 0.28.5
        cycler: 0.10.0
        cutadapt: '1.18'
        cryptography: 2.3.1
        cryptography-vectors: 2.3.1
        Click: '7.0'
        chardet: 3.0.4
        cffi: 1.11.5
        certifi: 2018.8.24
        CacheControl: 0.12.5
        bz2file: '0.98'
        bokeh: 0.13.0
        bleach: 3.0.2
        biopython: '1.68'
        biom-format: 2.1.7
        bibtexparser: 1.0.1
        backcall: 0.1.0
        asn1crypto: 0.24.0
        appnope: 0.1.0
        ijson: '2.3'
        mmtf-python: 1.0.2
        tzlocal: '1.3'
